model_name: bert-base-uncased
max_length: 512

train:
  lr: 2e-5
  batch_size: 8
  eval_batch_size: 8
  epochs: 15
  fp16: true

  logging_steps: 50
  eval_steps: 100
  save_steps: 100
  save_total_limit: 2

  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false

  report_to: ["none"]


